security: 
  basic: 
    enabled: false
 
management: 
  security: 
    enabled: false
 
spring: 
  jpa: 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate: 
      ddl-auto: update
 
greetingLanguage: English 16:57 / Spring Config
---
spring: 
  profiles: dev
greetingLanguage: French / Spring Config
---
spring: 
  profiles: prod
greetingLanguage: Spanish / Spring Config
